[View in Colaboratory](https://colab.research.google.com/github/muziejus/ai-atelier/blob/master/Copy_of_02_TensorsOpsVariablesStudentFinal.ipynb)

In [0]:
import tensorflow as tf
import tensorflow.contrib.eager as tfe
tf.enable_eager_execution()

In [25]:
ta = tf.convert_to_tensor([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
ta

<tf.Tensor: id=111, shape=(3, 10), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]], dtype=int32)>

## Tensors, Ops, & Variables


### Tensor Shapes & Slices

In [0]:
# can create tensors with convert_to_tensor
tensor = tf.convert_to_tensor([1,2,3,4,5])

In [3]:
# python indexing and slicing
tensor = tf.convert_to_tensor([1,2,3,4,5])
tensor[0:2]

<tf.Tensor: id=5, shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [0]:
# how to create a 2d tensor?
tensors = tf.convert_to_tensor([[1,2],[3,4]])

In [5]:
# indexing in 2d
tensors[0,0]

<tf.Tensor: id=11, shape=(), dtype=int32, numpy=1>

In [6]:
# slicing in 2d
tensors[:,0]

<tf.Tensor: id=16, shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

In [0]:
# tensors have a shape
# length of the shape is called the rank
# change number of elements and see shape

In [0]:
# tensors must have uniform shape! cannot have ragged shapes.
# this will error
tf.convert_to_tensor([[1,2],[3]])

In [7]:
# what is the shape of the below?
tensor = tf.convert_to_tensor([[1,1],[2,2],[3,3],[4,4],[5,5]])
tensor

<tf.Tensor: id=18, shape=(5, 2), dtype=int32, numpy=
array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]], dtype=int32)>

In [8]:
# often need to reshape tensors. Can reshape to any shape with same # of elements.
tensor = tf.convert_to_tensor([1,1,2,2,3,3,4,4,5,5])
tf.reshape(tensor, (5,2))

<tf.Tensor: id=22, shape=(5, 2), dtype=int32, numpy=
array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]], dtype=int32)>

In [0]:
# when reshaping, can have 1 (and only 1) wildcard dimension

In [9]:
tensor = tf.convert_to_tensor([1,1,2,2,3,3,4,4,5,5])
tf.reshape(tensor, (5,-1))

<tf.Tensor: id=26, shape=(5, 2), dtype=int32, numpy=
array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]], dtype=int32)>

In [10]:
tensor = tf.convert_to_tensor([1,1,2,2,3,3,4,4,5,5])
tf.reshape(tensor, (-1,2))

<tf.Tensor: id=30, shape=(5, 2), dtype=int32, numpy=
array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]], dtype=int32)>

### Ops & Shapes

In [0]:
tensor = tf.convert_to_tensor([1,2,3,4,5])

In [12]:
# python math operatos are overloaded into TF ops
tensor + tensor

<tf.Tensor: id=33, shape=(5,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10], dtype=int32)>

In [0]:
# shapes have to be compatible
tensor_1 = tf.convert_to_tensor([1,2,3,4,5])
tensor_2 = tf.convert_to_tensor([1,2,3])
tensor_1 + tensor_2

In [14]:
# Why shapes are really important:
# functions expect certain shapes
tf.losses.sigmoid_cross_entropy(
    tf.convert_to_tensor([[0.3], [0.6]]), 
    tf.convert_to_tensor([[0.0],[1.0]]))

<tf.Tensor: id=77, shape=(), dtype=float32, numpy=0.7032044>

In [0]:
# broken in comparison to above
tf.losses.sigmoid_cross_entropy(
    tf.convert_to_tensor([[0.3], [0.6]]), 
    tf.convert_to_tensor([0.0,1.0]))
# important to understand how functions & shape interact

In [15]:
# most tensor ops are vectorized by default
# will compute operation independently on each element in the tensor
tf.square(tensor)

<tf.Tensor: id=79, shape=(5,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25], dtype=int32)>

In [16]:
# same code will work on a more complex shape
tf.square(tf.convert_to_tensor([[1,2],[3,4]]))

<tf.Tensor: id=82, shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [17]:
# most operations support 'broadcasting'
# if you supply a smaller-dimensional tensor, it will expand it into the full shape
tensor + 1

<tf.Tensor: id=85, shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6], dtype=int32)>

In [0]:
# equivalent to above
tensor + tf.convert_to_tensor([1,1,1,1,1])

In [18]:
# the axis option can often be used to tune broadcasting behavior
# or make the operation happen at a certain level of the tensor
tf.reduce_mean(tf.convert_to_tensor([0, 2]), axis=0)

<tf.Tensor: id=88, shape=(), dtype=int32, numpy=1>

In [19]:
tf.reduce_mean(tf.convert_to_tensor([[0,2],[10,12]]), axis=0)

<tf.Tensor: id=91, shape=(2,), dtype=int32, numpy=array([5, 7], dtype=int32)>

In [20]:
tf.reduce_mean(tf.convert_to_tensor([[0,2],[10,12]]), axis=1)

<tf.Tensor: id=94, shape=(2,), dtype=int32, numpy=array([ 1, 11], dtype=int32)>

In [21]:
# dot product
tf.tensordot(
    tf.convert_to_tensor([2,2]),
    tf.convert_to_tensor([1,1]),
    axes=1
)

<tf.Tensor: id=108, shape=(), dtype=int32, numpy=4>

matrix multiplication

![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Matrix_multiplication_diagram_2.svg/313px-Matrix_multiplication_diagram_2.svg.png)

In [26]:
# rows dot columns
tf.matmul(
    tf.convert_to_tensor(
    [[1,2],
     [3,4]]
    ),
    tf.convert_to_tensor(
    [[1,2],
     [3,4]]
    )
)

<tf.Tensor: id=115, shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

### Variables

- Tensors are immutable
- Give motivation as to why
- Instead we use variables for state. Particularly model parameters

In [0]:
# tensors cannot be changed after they've been created.
tensor = tf.convert_to_tensor([1,2,3,4,5])
tensor[0] = 2

In [0]:
# instead, we use Variables to contain tensor values that may change over time

In [27]:
# seed variable with an initial value
v = tfe.Variable(tf.convert_to_tensor([1,2,3,4,5]))
v

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [28]:
# assign a new value
v.assign(tf.convert_to_tensor([1,1,2,2,2]))

<tf.Variable '' shape=(5,) dtype=int32, numpy=array([1, 1, 2, 2, 2], dtype=int32)>

In [0]:
# similar to +=
v.assign_add(tf.convert_to_tensor([1,1,1,1,1]))

In [0]:
# variables as important for computing gradients, will cover this in next section

### Challenges

In [29]:
# 1.
# recall computing the line a*x+b from previous section
# for now lets assume b = 0, and remove it from the equation
A = tf.convert_to_tensor([3])
x_values = tf.convert_to_tensor([0, 1, 2, 3])
A * x_values

<tf.Tensor: id=132, shape=(4,), dtype=int32, numpy=array([0, 3, 6, 9], dtype=int32)>

In [67]:
x_values

<tf.Tensor: id=313, shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

In [0]:
# How can we compute two lines simultanously, one with slope 3 and other with slope 4?
A = tf.convert_to_tensor([3, 4])# fill in
x_values = tf.convert_to_tensor([0, 1, 2, 3])

def two_lines(a):
  return tf.tensordot(x_values, a, axes=0)# fill in
def two_linesb(a):
  return tf.tensordot(a, x_values, axes=0)

In [63]:
two_linesb(A)

InvalidArgumentError: ignored

In [61]:
two_lines(A)
# desired output:
# <tf.Tensor: id=47, shape=(4, 2), dtype=int32, numpy=
# array([[ 0,  0],
#        [ 3,  4],
#        [ 6,  8],
#        [ 9, 12]], dtype=int32)>

# hint: get the shapes right

<tf.Tensor: id=298, shape=(4, 2), dtype=int32, numpy=
array([[ 0,  0],
       [ 3,  4],
       [ 6,  8],
       [ 9, 12]], dtype=int32)>

In [74]:
# 2.
# Suppose we have an 100x100 pixel image, with RBGA values for each pixel. 
# How would you represent that as a tensor? What would be the shape? (more than 1 possible answer)

tf.convert_to_tensor([[[255,255,255,1.0]], [[255,255,255,1.0]]])

<tf.Tensor: id=324, shape=(2, 1, 4), dtype=float32, numpy=
array([[[255., 255., 255.,   1.]],

       [[255., 255., 255.,   1.]]], dtype=float32)>

In [0]:
# 3.
# compute matrix multiply on two shape (2,2) tensors using tensordot, slicing, and reshape
# try computing the 0,0 entry first

tensorA = tf.convert_to_tensor(
    [[1,2],
     [3,4]])

tensorB = tf.convert_to_tensor(
    [[1,2],
     [3,4]])